online_priority: [2, 4, 1, 5]
offline_priority: [1, 5, 2, 4]
bins_for_pallets: [3]
num_pallets: 60
entrance_position: [0, 100, 0, 3]  # entrance position (x, y, z, bin_id)

bin_config:
  width: 50
  height: 300
  depth: 50
  min_adjust_length: 5
  weight_limit: 17